import { RespectCard } from '@/types/gathering';
import { PortfolioCard } from '@/types/portfolio';

export const todayRespecterDummy: {
  respecter: RespectCard & { projects: number };
  portfolio: PortfolioCard;
}[] = [
  {
    respecter: {
      id: 1,
      userId: 1,
      nickname: '박창협',
      profileImage: '/images/gathering/profile1.svg',
      spectrumImage: '/images/gathering/spectrum2.svg',
      portfolioImages: [
        '/images/gathering/thumbnail1.svg',
        '/images/gathering/thumbnail2.svg',
        '/images/gathering/thumbnail3.svg',
      ],
      major: 'UX/UI',
      minor: '웹디자인',
      badge: [
        '/images/gathering/badge1.svg',
        '/images/gathering/badge2.svg',
        '/images/gathering/badge3.svg',
        '/images/gathering/badge4.svg',
      ],
      following: 767,
      follower: 676,
      projects: 767,
    },
    portfolio: {
      id: 1,
      title: '작업제목',
      thumbnail: '/images/gathering/thumbnail1.svg',
      userProfile: '/images/gathering/profile1.svg',
      nickname: '박창협',
      hits: 767,
      likes: 676,
    },
  },
  {
    respecter: {
      id: 2,
      userId: 2,
      nickname: '박태영',
      profileImage: '/images/gathering/profile2.svg',
      spectrumImage: '/images/gathering/spectrum.svg',
      portfolioImages: [
        '/images/gathering/thumbnail2.svg',
        '/images/gathering/thumbnail3.svg',
        '/images/gathering/thumbnail4.svg',
      ],
      major: '프론트엔드',
      minor: 'UX/UI',
      badge: [
        '/images/gathering/badge2.svg',
        '/images/gathering/badge1.svg',
        '/images/gathering/badge4.svg',
        '/images/gathering/badge3.svg',
      ],
      following: 323,
      follower: 232,
      projects: 323,
    },
    portfolio: {
      id: 2,
      title: '작업제목',
      thumbnail: '/images/gathering/thumbnail2.svg',
      userProfile: '/images/gathering/profile2.svg',
      nickname: '박태영',
      hits: 323,
      likes: 232,
    },
  },
  {
    respecter: {
      id: 3,
      userId: 3,
      nickname: '안선영',
      profileImage: '/images/gathering/profile3.svg',
      spectrumImage: '/images/gathering/spectrum2.svg',
      portfolioImages: [
        '/images/gathering/thumbnail3.svg',
        '/images/gathering/thumbnail2.svg',
        '/images/gathering/thumbnail1.svg',
      ],
      major: 'UX/UI',
      minor: '웹디자인',
      badge: [
        '/images/gathering/badge3.svg',
        '/images/gathering/badge2.svg',
        '/images/gathering/badge4.svg',
        '/images/gathering/badge1.svg',
      ],
      following: 565,
      follower: 656,
      projects: 565,
    },
    portfolio: {
      id: 3,
      title: '작업제목',
      thumbnail: '/images/gathering/thumbnail3.svg',
      userProfile: '/images/gathering/profile3.svg',
      nickname: '안선영',
      hits: 565,
      likes: 656,
    },
  },
  {
    respecter: {
      id: 4,
      userId: 4,
      nickname: '정진',
      profileImage: '/images/gathering/profile4.svg',
      spectrumImage: '/images/gathering/spectrum4.svg',
      portfolioImages: [
        '/images/gathering/thumbnail4.svg',
        '/images/gathering/thumbnail5.svg',
        '/images/gathering/thumbnail3.svg',
      ],
      major: '백엔드',
      minor: '프론트엔드',
      badge: [
        '/images/gathering/badge2.svg',
        '/images/gathering/badge3.svg',
        '/images/gathering/badge4.svg',
        '/images/gathering/badge1.svg',
      ],
      following: 898,
      follower: 989,
      projects: 898,
    },
    portfolio: {
      id: 4,
      title: '작업제목',
      thumbnail: '/images/gathering/thumbnail5.svg',
      userProfile: '/images/gathering/profile4.svg',
      nickname: '정진',
      hits: 898,
      likes: 989,
    },
  },
];

export const respectGridCardDummy: RespectCard[] = [
  {
    id: 1,
    userId: 1,
    nickname: '고하은',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '기세준',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '김수진',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '서유빈',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안지은',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },

  {
    id: 3,
    userId: 3,
    nickname: '이다빈',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '조현재',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 1,
    userId: 1,
    nickname: '박창협',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '박태영',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안선영',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 4,
    userId: 4,
    nickname: '정진',
    profileImage: '/images/gathering/profile4.svg',
    spectrumImage: '/images/gathering/spectrum4.svg',
    portfolioImages: [
      '/images/gathering/thumbnail4.svg',
      '/images/gathering/thumbnail5.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: '백엔드',
    minor: '프론트엔드',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 898,
    follower: 989,
  },
  {
    id: 1,
    userId: 1,
    nickname: '고하은',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '기세준',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '김수진',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '서유빈',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안지은',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },

  {
    id: 3,
    userId: 3,
    nickname: '이다빈',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '조현재',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 1,
    userId: 1,
    nickname: '박창협',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '박태영',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안선영',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 4,
    userId: 4,
    nickname: '정진',
    profileImage: '/images/gathering/profile4.svg',
    spectrumImage: '/images/gathering/spectrum4.svg',
    portfolioImages: [
      '/images/gathering/thumbnail4.svg',
      '/images/gathering/thumbnail5.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: '백엔드',
    minor: '프론트엔드',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 898,
    follower: 989,
  },
  {
    id: 1,
    userId: 1,
    nickname: '고하은',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '기세준',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '김수진',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '서유빈',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안지은',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },

  {
    id: 3,
    userId: 3,
    nickname: '이다빈',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '조현재',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 1,
    userId: 1,
    nickname: '박창협',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '박태영',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안선영',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 4,
    userId: 4,
    nickname: '정진',
    profileImage: '/images/gathering/profile4.svg',
    spectrumImage: '/images/gathering/spectrum4.svg',
    portfolioImages: [
      '/images/gathering/thumbnail4.svg',
      '/images/gathering/thumbnail5.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: '백엔드',
    minor: '프론트엔드',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 898,
    follower: 989,
  },
  {
    id: 1,
    userId: 1,
    nickname: '고하은',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '기세준',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '김수진',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '서유빈',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안지은',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },

  {
    id: 3,
    userId: 3,
    nickname: '이다빈',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '조현재',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 1,
    userId: 1,
    nickname: '박창협',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '박태영',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안선영',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 4,
    userId: 4,
    nickname: '정진',
    profileImage: '/images/gathering/profile4.svg',
    spectrumImage: '/images/gathering/spectrum4.svg',
    portfolioImages: [
      '/images/gathering/thumbnail4.svg',
      '/images/gathering/thumbnail5.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: '백엔드',
    minor: '프론트엔드',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 898,
    follower: 989,
  },
  {
    id: 1,
    userId: 1,
    nickname: '고하은',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '기세준',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '김수진',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '서유빈',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안지은',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },

  {
    id: 3,
    userId: 3,
    nickname: '이다빈',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 2,
    userId: 2,
    nickname: '조현재',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 1,
    userId: 1,
    nickname: '박창협',
    profileImage: '/images/gathering/profile1.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail1.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge1.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
    ],
    following: 767,
    follower: 676,
  },
  {
    id: 2,
    userId: 2,
    nickname: '박태영',
    profileImage: '/images/gathering/profile2.svg',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail4.svg',
    ],
    major: '프론트엔드',
    minor: 'UX/UI',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge1.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge3.svg',
    ],
    following: 323,
    follower: 232,
  },
  {
    id: 3,
    userId: 3,
    nickname: '안선영',
    profileImage: '/images/gathering/profile3.svg',
    spectrumImage: '/images/gathering/spectrum2.svg',
    portfolioImages: [
      '/images/gathering/thumbnail3.svg',
      '/images/gathering/thumbnail2.svg',
      '/images/gathering/thumbnail1.svg',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/badge3.svg',
      '/images/gathering/badge2.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 565,
    follower: 656,
  },
  {
    id: 4,
    userId: 4,
    nickname: '정진',
    profileImage: '/images/gathering/profile4.svg',
    spectrumImage: '/images/gathering/spectrum4.svg',
    portfolioImages: [
      '/images/gathering/thumbnail4.svg',
      '/images/gathering/thumbnail5.svg',
      '/images/gathering/thumbnail3.svg',
    ],
    major: '백엔드',
    minor: '프론트엔드',
    badge: [
      '/images/gathering/badge2.svg',
      '/images/gathering/badge3.svg',
      '/images/gathering/badge4.svg',
      '/images/gathering/badge1.svg',
    ],
    following: 898,
    follower: 989,
  },
];
