import { RespectCard } from '@/types/gathering';

export const respectGridCardDummy: RespectCard[] = [
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
  {
    id: 1,
    userId: 123,
    nickname: '사용자닉네임',
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    spectrumImage: '/images/gathering/spectrum.svg',
    portfolioImages: [
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
      'https://dummyimage.com/100x100/74afe3/fff',
    ],
    major: 'UX/UI',
    minor: '웹디자인',
    badge: [
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
      '/images/gathering/spectrum.svg',
    ],
    following: 999,
    follower: 999,
  },
];
