import { GatheringCard } from '@/types/gathering';

export const gatheringCardDummy: GatheringCard[] = [
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 생활을 가능하도록 하는 서비스입니다🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 812,
    hits: 812,
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: 'Plantopia',
    content: '슬기로운 식집사 생활을 가능하도록 하는 서비스입니다🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
  },
  {
    id: 6,
    type: 'project',
    Dday: 3,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 812,
    hits: 812,
  },
  {
    id: 7,
    type: 'project',
    Dday: 4,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
  },
  {
    id: 8,
    type: 'project',
    Dday: 5,
    title: 'Plantopia',
    content: '슬기로운 식집사 생활을 가능하도록 하는 서비스입니다🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 생활을 가능하도록 하는 서비스입니다🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 812,
    hits: 812,
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: 'Plantopia',
    content: '슬기로운 식집사 생활을 가능하도록 하는 서비스입니다🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
  },
  {
    id: 6,
    type: 'study',
    Dday: 3,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 812,
    hits: 812,
  },
  {
    id: 7,
    type: 'study',
    Dday: 4,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
  },
  {
    id: 8,
    type: 'study',
    Dday: 5,
    title: 'Plantopia',
    content: '슬기로운 식집사 생활을 가능하도록 하는 서비스입니다🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
  },
];

export const gatheringGridCardDummy: GatheringCard[] = [
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
    skills: ['Java', 'JavaScript', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
    skills: ['Java', 'JavaScript', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
    skills: ['Java', 'JavaScript', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
    skills: ['Java', 'JavaScript', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
    skills: ['Java', 'JavaScript', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    jobs: ['기획'],
    way: '오프라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    skills: ['Figma'],
    jobs: ['디자인'],
    way: '온라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    jobs: ['디자인'],
    skills: ['Figma', 'JavaScript'],
    way: '온라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    jobs: ['디자인', '개발'],
    positions: ['디자이너', '프론트엔드'],
    skills: ['Figma', 'JavaScript'],
    way: '온라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    jobs: ['디자인', '개발'],
    positions: ['디자이너', '프론트엔드'],
    skills: ['Figma', 'JavaScript'],
    way: '온라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    jobs: ['디자인', '개발'],
    positions: ['디자이너', '프론트엔드'],
    skills: ['Figma', 'JavaScript'],
    way: '온라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    jobs: ['디자인', '개발'],
    positions: ['디자이너', '프론트엔드'],
    skills: ['Figma', 'JavaScript'],
    way: '온라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    jobs: ['디자인', '개발'],
    positions: ['디자이너', '프론트엔드'],
    skills: ['Figma', 'JavaScript'],
    way: '온라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    jobs: ['디자인', '개발'],
    positions: ['디자이너', '프론트엔드'],
    skills: ['Figma', 'JavaScript'],
    way: '온라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    jobs: ['디자인', '개발'],
    positions: ['디자이너', '프론트엔드'],
    skills: ['Figma', 'JavaScript'],
    way: '온라인',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'study',
    Dday: 3,
    title: '스터디 이름은 1줄까지 표시됩니다.',
    content: '스터디 내용은 2줄까지 표시됩니다.',
    subject: '스터디 주제',
    teamName: '팀 이름',
    tag: '태그',
    capacity: [1, 5],
    deadline: new Date(),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
];
