import { GatheringCard } from '@/types/gathering';

export const gatheringCardDummy: GatheringCard[] = [
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['디자인'],
    positions: ['디자이너'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '디자인'],
    positions: ['PM', '디자이너'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['디자인'],
    positions: ['디자이너'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '백엔드'],
    way: '오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['디자인'],
    positions: ['디자이너', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['디자인'],
    positions: ['디자이너'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '디자인'],
    positions: ['PM', '디자이너'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['디자인'],
    positions: ['디자이너'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '백엔드'],
    way: '오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['디자인'],
    positions: ['디자이너', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'study',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'study',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'study',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'study',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
  {
    id: 5,
    type: 'study',
    Dday: 3,
    title: '부릉',
    content: '차쟁이들이 만드는 건강한 자동차 취미 공간입니다🚗',
    subject: '모빌리티(교통)',
    teamName: '부르릉',
    tag: '태그',
    member: {
      PM: 2,
      frontEnd: 4,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 24,
    hits: 1012,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 1,
    type: 'project',
    Dday: 1,
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰을 만들어 봐요🌸',
    subject: '이커머스',
    teamName: '향기나조',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 217,
    skills: ['React', 'Spring', 'Figma', 'Xd'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '서비스기획', '디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 2,
    type: 'project',
    Dday: 2,
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어 나가요🌱',
    subject: '기타',
    teamName: '7ㅏ보자고',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 2,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile2.svg',
    comments: 10,
    hits: 712,
    skills: ['React', 'Spring', 'Figma'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '온/오프라인',
  },
  {
    id: 3,
    type: 'project',
    Dday: 2,
    title: 'Book-It',
    content: '온라인 코딩 교육 플랫폼 개발에 참여해보세요📚',
    subject: '교육',
    teamName: '모나리자',
    tag: '태그',
    member: {
      PM: 1,
      designer: 1,
      frontEnd: 2,
      backEnd: 4,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile3.svg',
    comments: 2,
    hits: 62,
    skills: ['React', 'Figma'],
    jobs: ['기획', '개발', '디자인'],
    positions: ['PM', '디자이너', '프론트엔드', '백엔드'],
    way: '온라인',
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    subject: '기타',
    teamName: '야옹',
    tag: '태그',
    member: {
      designer: 2,
      frontEnd: 2,
      backEnd: 3,
    },
    deadline: new Date(),
    profileImage: '/images/gathering/profile1.svg',
    comments: 3,
    hits: 346,
    skills: ['React', 'Xd'],
    jobs: ['개발', '디자인'],
    positions: ['디자이너', '프론트엔드', '백엔드'],
    way: '오프라인',
  },
];
