import { GatheringCard } from '@/types/gathering';

export const gatheringCardDummy: GatheringCard[] = [
  {
    id: 1,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 2,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 3,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 4,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 5,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 6,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 7,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 8,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 9,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 10,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 11,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
  {
    id: 12,
    type: 'project',
    Dday: 3,
    title: '프로젝트 이름은 1줄까지 표시됩니다.',
    content: '프로젝트 내용은 2줄까지 표시됩니다.',
    subject: '프로젝트 주제',
    teamName: '팀 이름',
    tag: '태그',
    member: {
      planner: 1,
      designer: 3,
      frontEnd: 3,
    },
    deadline: new Date('2024. 01. 12'),
    profileImage: 'https://dummyimage.com/100x100/74afe3/fff',
    comments: 812,
    hits: 812,
  },
];
