import { Retrospect, RetrospectCard } from '@/types/gathering';

export const retrospectCardDummy: RetrospectCard[] = [
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
  {
    id: 1,
    type: 'project',
    title: '마이펫',
    content: '반려동물을 위한 서비스를 기획하고 개발해요😺',
    teamName: '야옹',
    thumbnail: '/images/gathering/thumbnail4.svg',
    profileImage: '/images/gathering/profile4.svg',
    likes: 363,
    hits: 636,
    tags: ['반려동물', '야옹', '멍멍'],
  },
  {
    id: 2,
    type: 'project',
    title: 'Fragrant',
    content: '나만의 온라인 향수 쇼핑몰🌸',
    teamName: '향기나조',
    thumbnail: '/images/gathering/thumbnail2.svg',
    profileImage: '/images/gathering/profile2.svg',
    likes: 232,
    hits: 323,
    tags: ['향수', '바이레도'],
  },
  {
    id: 3,
    type: 'project',
    title: 'Plantopia',
    content: '슬기로운 식집사 문화를 만들어요🌱',
    teamName: '7ㅏ보자고',
    thumbnail: '/images/gathering/thumbnail3.svg',
    profileImage: '/images/gathering/profile3.svg',
    likes: 131,
    hits: 313,
    tags: ['식물', '플랜테리어'],
  },
  {
    id: 4,
    type: 'project',
    title: '토끼책방',
    content: 'e-book 서비스 플랫폼입니다🐰',
    teamName: '깡총',
    thumbnail: '/images/gathering/thumbnail5.svg',
    profileImage: '/images/gathering/profile5.svg',
    likes: 131,
    hits: 313,
    tags: ['책벌레'],
  },
  {
    id: 5,
    type: 'project',
    title: '부릉',
    content: '차쟁이들이 만들어 가는 건전한 자동차 모임 서비스입니다🚗',
    teamName: '부르릉',
    thumbnail: '/images/gathering/thumbnail1.svg',
    profileImage: '/images/gathering/profile1.svg',
    likes: 767,
    hits: 676,
    tags: ['빵빵'],
  },
];

export const retrospectDummy: Retrospect[] = [
  {
    id: 1,
    type: 'project',
    category: '사이드 프로젝트',
    title: '4tfolio',
    subject: '여행',
    introduction: '프로젝트 소개 ~~',
    period: [new Date(2023 - 12 - 21), new Date(2023 - 12 - 28)],
    thumbnail: '/images/gathering/thumbnail1.svg',
    teamName: 'team4',
    members: [
      {
        userId: 1,
        name: '고하은',
        userProfile: '/images/gathering/profile1.svg',
        spectrumImage: '/images/gathering/spectrum2.svg',
        position: 'PM',
        isLeader: true,
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 2,
        name: '기세준',
        userProfile: '/images/gathering/profile2.svg',
        spectrumImage: '/images/gathering/spectrum3.svg',
        position: '디자이너',
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 3,
        name: '김수진',
        userProfile: '/images/gathering/profile3.svg',
        spectrumImage: '/images/gathering/spectrum4.svg',
        position: '프론트엔드',
        retrospect:
          '인원은 적었지만 모든 팀원분들이 열정있게 참여해주셔서 부족함이 없었던 것 같아요! 사벤져스 최고!!🥳',
      },
      {
        userId: 4,
        name: '박창협',
        userProfile: '/images/gathering/profile4.svg',
        spectrumImage: '/images/gathering/spectrum1.svg',
        position: '백엔드',
        retrospect:
          '좋은 분들과 함께해서 힘들지 않았습니다! 현업에서 더 멋진 모습으로 만나요😎',
      },
    ],
    skills: ['React', 'Typescript'],
    tags: ['교육'],
  },
  {
    id: 2,
    type: 'project',
    category: '사이드 프로젝트',
    title: '4tfolio',
    subject: '여행',
    introduction: '프로젝트 소개 ~~',
    retrospect:
      '초기 브랜딩은 모든 팀원들이 함께 참여하면서 친근감 있는 캐릭터를 어떻게 잡을까 고민했던 것 같아요. 그 가운데 고양이 캐릭터가 탄생했습니다. 그 가운데 고양이 캐릭터가 탄생했습니다.',
    period: [new Date(2023 - 12 - 21), new Date(2023 - 12 - 28)],
    thumbnail: '/images/gathering/thumbnail1.svg',
    teamName: 'team4',
    members: [
      {
        userId: 1,
        name: '박태영',
        userProfile: '/images/gathering/profile3.svg',
        spectrumImage: '/images/gathering/spectrum4.svg',
        position: 'PM',
        isLeader: true,
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 2,
        name: '서유빈',
        userProfile: '/images/gathering/profile2.svg',
        spectrumImage: '/images/gathering/spectrum3.svg',
        position: '디자이너',
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 3,
        name: '안선영',
        userProfile: '/images/gathering/profile1.svg',
        spectrumImage: '/images/gathering/spectrum2.svg',
        position: '프론트엔드',
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 4,
        name: '안지은',
        userProfile: '/images/gathering/profile4.svg',
        spectrumImage: '/images/gathering/spectrum1.svg',
        position: '백엔드',
        retrospect:
          '능력있는 팀원들이랑 함께해서 성장할 수 있는 기회가 되었던 것 같습니다. 다들 고생 많으셨습니다!',
      },
    ],
    skills: ['React', 'Typescript'],
    tags: ['교육'],
  },
  {
    id: 3,
    type: 'project',
    category: '사이드 프로젝트',
    title: '4tfolio',
    subject: '여행',
    introduction: '프로젝트 소개 ~~',
    retrospect:
      '초기 브랜딩은 모든 팀원들이 함께 참여하면서 친근감 있는 캐릭터를 어떻게 잡을까 고민했던 것 같아요. 그 가운데 고양이 캐릭터가 탄생했습니다. 그 가운데 고양이 캐릭터가 탄생했습니다.',
    period: [new Date(2023 - 12 - 21), new Date(2023 - 12 - 28)],
    thumbnail: '/images/gathering/thumbnail1.svg',
    teamName: 'team4',
    members: [
      {
        userId: 1,
        name: '이다빈',
        userProfile: '/images/gathering/profile2.svg',
        spectrumImage: '/images/gathering/spectrum2.svg',
        position: 'PM',
        isLeader: true,
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 2,
        name: '정진',
        userProfile: '/images/gathering/profile1.svg',
        spectrumImage: '/images/gathering/spectrum3.svg',
        position: '디자이너',
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 3,
        name: '조현재',
        userProfile: '/images/gathering/profile3.svg',
        spectrumImage: '/images/gathering/spectrum4.svg',
        position: '프론트엔드',
        retrospect:
          '비록 짧은 시간이었지만 팀원분들께 정말 많이 배울 수 있어서 의미 있는 시간이었습니다! 고생 많으셨고 앞으로도 파이팅!!',
      },
    ],
    skills: ['React', 'Typescript'],
    tags: ['교육'],
  },
  {
    id: 4,
    type: 'project',
    category: '사이드 프로젝트',
    title: '4tfolio',
    subject: '여행',
    introduction: '프로젝트 소개 ~~',
    retrospect:
      '초기 브랜딩은 모든 팀원들이 함께 참여하면서 친근감 있는 캐릭터를 어떻게 잡을까 고민했던 것 같아요. 그 가운데 고양이 캐릭터가 탄생했습니다. 그 가운데 고양이 캐릭터가 탄생했습니다.',
    period: [new Date(2023 - 12 - 21), new Date(2023 - 12 - 28)],
    thumbnail: '/images/gathering/thumbnail1.svg',
    teamName: 'team4',
    members: [
      {
        userId: 1,
        name: '고하은',
        userProfile: '/images/gathering/profile1.svg',
        spectrumImage: '/images/gathering/spectrum2.svg',
        position: 'PM',
        isLeader: true,
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 2,
        name: '기세준',
        userProfile: '/images/gathering/profile2.svg',
        spectrumImage: '/images/gathering/spectrum3.svg',
        position: '디자이너',
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 3,
        name: '김수진',
        userProfile: '/images/gathering/profile3.svg',
        spectrumImage: '/images/gathering/spectrum4.svg',
        position: '프론트엔드',
        retrospect:
          '인원은 적었지만 모든 팀원분들이 열정있게 참여해주셔서 부족함이 없었던 것 같아요! 사벤져스 최고!!🥳',
      },
      {
        userId: 4,
        name: '박창협',
        userProfile: '/images/gathering/profile4.svg',
        spectrumImage: '/images/gathering/spectrum1.svg',
        position: '백엔드',
        retrospect:
          '좋은 분들과 함께해서 힘들지 않았습니다! 현업에서 더 멋진 모습으로 만나요😎',
      },
    ],
    skills: ['React', 'Typescript'],
    tags: ['교육'],
  },
  {
    id: 5,
    type: 'project',
    category: '사이드 프로젝트',
    title: '4tfolio',
    subject: '여행',
    introduction: '프로젝트 소개 ~~',
    retrospect:
      '초기 브랜딩은 모든 팀원들이 함께 참여하면서 친근감 있는 캐릭터를 어떻게 잡을까 고민했던 것 같아요. 그 가운데 고양이 캐릭터가 탄생했습니다. 그 가운데 고양이 캐릭터가 탄생했습니다.',
    period: [new Date(2023 - 12 - 21), new Date(2023 - 12 - 28)],
    thumbnail: '/images/gathering/thumbnail1.svg',
    teamName: 'team4',
    members: [
      {
        userId: 1,
        name: '박태영',
        userProfile: '/images/gathering/profile3.svg',
        spectrumImage: '/images/gathering/spectrum4.svg',
        position: 'PM',
        isLeader: true,
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 2,
        name: '서유빈',
        userProfile: '/images/gathering/profile2.svg',
        spectrumImage: '/images/gathering/spectrum3.svg',
        position: '디자이너',
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 3,
        name: '안선영',
        userProfile: '/images/gathering/profile1.svg',
        spectrumImage: '/images/gathering/spectrum2.svg',
        position: '프론트엔드',
        retrospect:
          '내가 발표라니 거짓말...🥹 사벤져스짱!! 다들 수고하셨어요💗 모두 앞으로의 행보도 응원할게요🍀',
      },
      {
        userId: 4,
        name: '안지은',
        userProfile: '/images/gathering/profile4.svg',
        spectrumImage: '/images/gathering/spectrum1.svg',
        position: '백엔드',
        retrospect:
          '능력있는 팀원들이랑 함께해서 성장할 수 있는 기회가 되었던 것 같습니다. 다들 고생 많으셨습니다!',
      },
    ],
    skills: ['React', 'Typescript'],
    tags: ['교육'],
  },
];
