import { DetailPortfolio, SimplePortfolio } from '@/types/main';

export const DetailPortfolioDummy: DetailPortfolio[] = [
  {
    id: 1,
    image : "/images/main/portfolio/photo1.png",
    category: "웹디자인",
    title: "기후 프로젝트 : The climate Reality Project Website Redesign",
    content: "기후위기를 더 이상 외면할 수 없음과 일상에서의 실천방법을 전달하고 사용자들이 기후 프로젝트 내 교육과 캠페인에 쉽게 참여할 수 있도록 개편하였습니다.",
    name: "김수진",
    view: 234,
    like: 124,
  },
  {
    id: 2,
    image : "/images/main/portfolio/photo3.png",
    category: "UI/UX",
    title: "Yota 요리타이머",
    content: "요리를 시작한 젊은층을 위한 요리 타이머 앱입니다.",
    name: "기세준",
    view: 233,
    like: 12,
  },
  {
    id: 3,
    image : "/images/main/portfolio/photo2.png",
    category: "UI/UX",
    title: "My docent UI/UX Design",
    content: "마이 도슨트는 우리 모두를 예술인의 감상속으로 인도하며 가장 쉽고 빠르게 예술계의 모든 것을 큐레이션 합니다.",
    name: "고하은",
    view: 9030,
    like: 213,
  },
  {
    id: 4,
    image : "/images/main/portfolio/photo4.png",
    category: "UI/UX",
    title: "Yota 요리타이머",
    content: "요리를 시작한 젊은층을 위한 요리 타이머 앱입니다.",
    name: "김수진",
    view: 234,
    like: 124,
  },
  {
    id: 5,
    image : "/images/main/portfolio/photo5.png",
    category: "서비스기획",
    title: "Texture",
    content: "‘텍스처'는 잘 읽고, 잘 기록하는 것에 대한 고민에서 출발했습니다.",
    name: "서유빈",
    view: 443,
    like: 53,
  },
  {
    id: 6,
    image : "/images/main/portfolio/photo6.png",
    category: "UI/UX",
    title: "기후 프로젝트 : The climate Reality Project Website Redesign",
    content: "기후위기를 더 이상 외면할 수 없음과 일상에서의 실천방법을 전달하고 사용자들이 기후 프로젝트 내 교육과 캠페인에 쉽게 참여할 수 있도록 개편하였습니다.",
    name: "안선영",
    view: 234,
    like: 124,
  }]


export const SimplePortfolioDummy: SimplePortfolio[] = [
    {
      id: 1,
      image : "/public/images/main/portfolio/photo1.png",
      category: "UI/UX",
      title: "유니클로 x 유니키스트",
      name: "안지은",
      view: 344,
      like: 63,
    },
    {
        id: 2,
        image : "/public/images/main/portfolio/photo2.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "루나",
        view: 5423,
        like: 234,
      },
      {
        id: 3,
        image : "/public/images/main/portfolio/photo3.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 4,
        image : "/public/images/main/portfolio/photo4.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 5,
        image : "/public/images/main/portfolio/photo5.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 6,
        image : "/public/images/main/portfolio/photo6.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 7,
        image : "/public/images/main/portfolio/photo7.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 8,
        image : "/public/images/main/portfolio/photo8.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 9,
        image : "/public/images/main/portfolio/photo9.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 10,
        image : "/public/images/main/portfolio/photo10.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 11,
        image : "/public/images/main/portfolio/photo11.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 12,
        image : "/public/images/main/portfolio/photo12.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },
      {
        id: 13,
        image : "/public/images/main/portfolio/photo13.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      },     
      {
        id: 14,
        image : "/public/images/main/portfolio/photo14.png",
        category: "UI/UX",
        title: "혈당 변화 관리 앱",
        name: "안지은",
        view: 344,
        like: 63,
      }
    ]